### ISSUE TITLE
takeWhileAntitone, dropWhileAntitone and spanAntitone

### ISSUE THREAD

**Issue by MathiasVP** [sgraf812/pomaps#1]
Love the pomaps library! It was just what I needed to get some code running super fast! Would it be possible to add support for the following functions?

> takeWhileAntitone :: (k -> Bool) -> POMap k a -> POMap k a
> dropWhileAntitone :: (k -> Bool) -> POMap k a -> POMap k a
> spanAntitone :: (k -> Bool) -> POMap k a -> (POMap k a, POMap k a)

**Comment by sgraf812** [comment]
I'm glad you like it! I'll have time to think about how to add those this weekend.

**Comment by sgraf812** [comment]
After thinking about it, it's not obvious to me which notion of antitone you are referring to, or what semantics you expect from those functions. Could give an example for `takeWhileAntitone`?

**Comment by sgraf812** [comment]
Ah, sorry. You're probably referring to [`takeWhileAntitone` from `Data.Map`](https://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Map-Internal.html#v:takeWhileAntitone).

**Comment by sgraf812** [comment]
[Released as 0.0.1.0](https://hackage.haskell.org/package/pomaps-0.0.1.0/docs/Data-POMap-Strict.html#v:takeWhileAntitone).
