### ISSUE TITLE
toAscList partiallly ordered elements

### ISSUE THREAD

**Issue by massudaw** [sgraf812/pomaps#2]
I don't know if is possible. But one huge feature that I missed while trying to use this library is a toAscList method that returns partially ordered elements. 

If it is possible can you give me hints on how to implement it?

**Comment by sgraf812** [comment]
`toAscList` probably doesn't make much sense for incomparable elements, but any partial order can be linearised/topologically sorted. I'll give this some ~~sort~~ thought.

**Comment by sgraf812** [comment]
[Here you go](https://hackage.haskell.org/package/pomaps-0.0.2.0/docs/Data-POMap-Strict.html#v:toLinearisation)
